### ISSUE TITLE
Support for Telegraf + UDP

### ISSUE THREAD

**Issue by pshrosbree** [AppMetrics/InfluxDB#17]
Currently connecting to InfluxDB via HTTP is well supported.
Another common setup with InfluxDB is to distribute Telegraf agents across hosts which then submit the data to database.

Telegraf supports a variety of protocols however UDP can be very beneficial as it is fire and forget.

(Original request at: https://github.com/alhardy/AppMetrics/issues/152)

**Comment by Alessar** [comment]
Sending metrics from AppMetrics into Telegraf can be made with using Sockets layer.
New feature is implemented in https://github.com/AppMetrics/Reporting/pull/50
It allows sending metrics via TCP and UDP protocols and with using unix domain sockets.

**Comment by alhardy** [comment]
Fixed by https://github.com/AppMetrics/Reporting/pull/50
