### ISSUE TITLE
Create db if not existing

### ISSUE THREAD

**Issue by gickis** [AppMetrics/InfluxDB#20]
Would be nice that app.metrics influxdb reporter will create database if it was not created

**Comment by alhardy** [comment]
I think in many cases an application wouldn't have such permission. For those that decide it's OK, it could be done just as easily outside App Metrics on app startup. Thoughts?

**Comment by gickis** [comment]
Agree with you, in most cases there is not root rights to influxdb instance. But on other hand, there is so easy to implement it, so maybe in future would be nice to have this feature as useful addition.

**Comment by alhardy** [comment]
I'll think about it again once a stable 2.0 release goes out. I guess I can think about it like getting started with EF which creates db tables on startup to make the dev experience a little better ;)

**Comment by RouR** [comment]
Please add this feature.
Heapster and Telegraf do it. Same behavior is expected.
It does not need any additional permissions (InfluxDB does not have any public endpoints, and used in local net only).

**Comment by alhardy** [comment]
Already done
