### ISSUE TITLE
No metrics send to influxdb

### ISSUE THREAD

**Issue by sorcer1** [AppMetrics/InfluxDB#37]
Hello,

I try to send metrics to influxdb (with grafana) but no metrics was sent to influxdb.
After sending multiple requests to my dotnet core web api i query influxdb and is empty :

> Connected to http://localhost:8086 version 1.6.0
> InfluxDB shell version: 1.6.0
> > SHOW DATABASES
> name: databases
> name
> ----
> _internal
> appmetrics
> > USE appmetrics
> Using database appmetrics
> > SELECT * FROM /.*/
> >

This why my metrics is configured :
```
   var metrics = new MetricsBuilder()
                .Report.ToInfluxDb(
                    options => {
                        options.InfluxDb.BaseUri = new Uri("http://127.0.0.1:8086");
                        options.InfluxDb.Database = "appmetrics";
                        options.InfluxDb.CreateDataBaseIfNotExists = true;
                        options.FlushInterval = TimeSpan.FromSeconds(5);
                    })
                .Build();

            services.AddMetrics(metrics);
            services.AddMetricsTrackingMiddleware();
            services.AddMetricsReportScheduler();
```

`services.AddMvc().AddMetrics();`

`app.UseMetricsAllMiddleware();`

What's wrong ?

**Comment by alhardy** [comment]
Check out the docs https://www.app-metrics.io/web-monitoring/aspnet-core/reporting/
