### ISSUE TITLE
Setting up InfluxDb in the config

### ISSUE THREAD

**Issue by siberianguy** [AppMetrics/InfluxDB#42]
All the samples I was able to find were specifying Report.ToInfluxDb in the code like this:

```
.ConfigureMetricsWithDefaults((hostingContext, metricsContext) => metricsContext.Configuration
                    .ReadFrom(hostingContext.Configuration)
                    .Report.ToInfluxDb(.../manually read settings/)
```

Is there a way to automate it, so the settings for Report are read from the appsettings.json similar to generic AppMetrics settings in .ReadFrom(hostingContext.Configuration)?

**Comment by alhardy** [comment]
ATM there is no extension to taking a configuration instance, easiest way would be to bind an instance of the influx options to your configuration section and pass in that

**Comment by siberianguy** [comment]
Could you please point me to a sample of how this (or something remotely similar) could be done?

**Comment by alhardy** [comment]
```
var options = new InfluxDbOptions();
configuration.GetSection(nameof(InfluxDbOptions)).Bind(options);
```

**Comment by siberianguy** [comment]
I'm a little confused whether it's possible to integrate reading a section into the following sample:

```
                .ConfigureMetricsWithDefaults((hostingContext, metricsContext) => metricsContext.Configuration
                    .ReadFrom(hostingContext.Configuration)
                    .Report.ToInfluxDb(hostingContext.Configuration.GetSection("InfluxDb")["BaseUri"],
                        hostingContext.Configuration.GetSection("InfluxDb")["Database"],
                        TimeSpan.FromSeconds(2)))
```
